### ISSUE TITLE
It doesn't seem to be recognized when inserting a table into a markdown-based table or content.

### ISSUE THREAD

**Issue by donghyun-daniel** [themefisher/twenty-twenty-hugo#11]
I'm adding and editing blog entries on forestry.io, and I don't know how to deal with tables and images, just like the title says. I can't upload it in the format I want even if I edit it in the markdown format in raw editor.

**Comment by somratpro** [comment]
Hello @donghyun-daniel 

You can follow this markdown cheatsheet https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables

**Comment by somratpro** [comment]
Hello @donghyun-daniel 

I am going to close this issue. If you face any more issue, feel free to re-open it, or create a new issue, thank you...
