### ISSUE TITLE
Blog posts: date display incorrect and inconsistent

### ISSUE THREAD

**Issue by matt-tum** [themefisher/twenty-twenty-hugo#12]
Hi there, I discovered an issue with the display of the date in blog posts in this theme and haven't been able to correct the code myself.

Regardless of the date that is specified in the markdown file in content/blog/... on the front page the displayed date is usually the 6th of a month, where as, when opening the post itself the date becomes the 20th of a month. I've tried this out with a couple different dates, it always comes down to the same. Please see the screenshots of an example date in December 2020. Thanks!

<img width="244" alt="Screenshot 2021-01-08 at 08 03 35" src="https://user-images.githubusercontent.com/62663103/103985307-fd2e3c80-5188-11eb-8cc4-30a5de55e94f.png">
<img width="181" alt="Screenshot 2021-01-08 at 08 03 11" src="https://user-images.githubusercontent.com/62663103/103985311-fdc6d300-5188-11eb-985b-eb21d4bcf251.png">
<img width="410" alt="Screenshot 2021-01-08 at 08 03 21" src="https://user-images.githubusercontent.com/62663103/103985312-fe5f6980-5188-11eb-91c3-bb547ac7b4e9.png">

**Comment by somratpro** [comment]
@matt-tum 
Thanks for your concern. We fixed the issue. Please download the latest code and enjoy!
